- name: Emmanuel Noutahi
  email: emmanuel.noutahi@hotmail.ca
  aliases:
  - maclandrol
  num_commits: 21
  first_commit: 2020-10-25 10:15:22
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  aliases:
  - hadim
  alternate_emails:
  - hadim@users.noreply.github.com
  num_commits: 29
  first_commit: 2020-10-24 11:46:22
- name: michelml
  email: michmoreau.l@gmail.com
  num_commits: 8
  first_commit: 2021-02-25 15:48:52
- name: Honoré Hounwanou
  email: mercuryseries@gmail.com
  num_commits: 1
  first_commit: 2021-02-12 17:01:32
- name: Therence1
  email: 38595485+Therence1@users.noreply.github.com
  num_commits: 3
  first_commit: 2021-04-03 17:31:09
- name: mike
  email: michael@invivoai.com
  num_commits: 3
  first_commit: 2021-03-30 16:03:51
- name: Ishan Kumar
  email: ishankumar216@gmail.com
  num_commits: 5
  first_commit: 2021-05-10 11:45:15
- name: deepsource-autofix[bot]
  email: 62050782+deepsource-autofix[bot]@users.noreply.github.com
  num_commits: 1
  first_commit: 2021-07-19 17:58:37
- name: DeepSource Bot
  email: bot@deepsource.io
  num_commits: 1
  first_commit: 2021-07-14 17:41:40
- name: Julien Horwood
  email: julien@invivoai.com
  num_commits: 7
  first_commit: 2022-01-26 17:14:26
