site_name: "datamol"
site_description: "A python library to work with molecules. Built on top of RDKit."
repo_url: "https://github.com/datamol-org/datamol"
repo_name: "datamol-org/datamol"
copyright: Copyright 2020 - 2021 Valence

site_url: ""
remote_branch: "gh-pages"
use_directory_urls: false
docs_dir: "docs"

nav:
  - Overview: index.md
  - Usage: usage.md
  - Tutorials:
      - The Basics: tutorials/The_Basics.ipynb
      - Preprocessing Molecules: tutorials/Preprocessing_Molecules.ipynb
      - Cluster Molecules: tutorials/Cluster_Molecules.ipynb
      - Fragment and Scaffold: tutorials/Fragment_and_Scaffold.ipynb
      - Working with local and remote data: tutorials/Filesystem.ipynb
  - API:
      - datamol: api/datamol.md
      - datamol.descriptors: api/datamol.descriptors.md
      - datamol.conformers: api/datamol.conformers.md
      - datamol.viz: api/datamol.viz.md
      - datamol.fragment: api/datamol.fragment.md
      - datamol.scaffold: api/datamol.scaffold.md
      - datamol.reactions: api/datamol.reactions.md
      - datamol.actions: api/datamol.actions.md
      - datamol.molar: api/datamol.molar.md
      - datamol.utils: api/datamol.utils.md

  - Contribute: contribute.md
  - License: license.md

theme:
  name: material
  # NOTE(hadim): to customize the material primary and secondary
  # color check `docs/assets/css/datamol-custom.css`.
  features:
    - navigation.expand
  favicon: images/logo.png
  logo: images/logo.png

extra_css:
  - assets/css/custom.css
  - assets/css/custom-datamol.css

extra_javascript:
  - assets/js/google-analytics.js

markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  # For `tab_length=2` in the markdown extension
  # See https://github.com/mkdocs/mkdocs/issues/545
  - mdx_truly_sane_lists
  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - search

  - mkdocstrings:
      watch:
        - datamol/
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
            - sys.path.append("datamol")
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: true
            heading_level: 4
            show_root_full_path: false

  - mkdocs-jupyter:
      execute: false
      # kernel_name: python3

  - mike:
      version_selector: true

extra:
  version:
    # Multi versioning provider for mkdocs-material (used for the JS selector)
    provider: mike
