name: doc

on:
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup conda
        # see https://github.com/mamba-org/provision-with-micromamba/issues/54
        uses: mamba-org/provision-with-micromamba@755a9542150cc9dedd1c1dd95b963460ec320939
        with:
          environment-file: false
          cache-downloads: true

      - name: Install Dependencies
        run: |
          micromamba activate
          micromamba create -n datamol -f env.yml

      - name: Install library
        run: |
          micromamba activate datamol
          python -m pip install .

      - name: Deploy the doc
        run: |
          micromamba activate datamol

          echo "Configure git"
          git config --global user.name 'hadim'
          git config --global user.email 'hadim@users.noreply.github.com'

          echo "Get the gh-pages branch"
          git fetch origin gh-pages

          TAG_OR_BRANCH_NAME=${GITHUB_REF##*/}

          if [ $TAG_OR_BRANCH_NAME = "main" ]; then
            echo "Build and deploy the doc on main"
            mike deploy --push --force main
          else
            echo "Build and deploy the doc on $TAG_OR_BRANCH_NAME"

            mike deploy --push --force stable
            mike deploy --push --force $TAG_OR_BRANCH_NAME
          fi
