name: test

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        rdkit-version: ["2021.09", "2022.03"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yml
          environment-name: datamol
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
            rdkit=${{ matrix.rdkit-version }}

      - name: Install library
        run: python -m pip install -e . # `-e` required for correct `coverage` run.

      - name: Run tests
        run: pytest

      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false
          env_vars: ${{ matrix.os }},${{ matrix.python-version }},${{ matrix.rdkit-version }}

      - name: Test building the doc
        run: mkdocs build
